import type { RenderOptions, ViewData, ViewScope } from "./types.js";
import { STYLES } from "./styles.js";
import { CLIENT_JS } from "./client.js";
import { ICONS } from "./icons.js";

export function renderHtml(data: ViewData, opts: RenderOptions): string {
  const preparedData = prepareDataBlob(data, opts);
  const jsonBlob = JSON.stringify(preparedData).replace(/<\//g, "<\\/");

  const tree = renderTree(data.scopes);
  const graphSection = opts.includeGraph && data.has_index
    ? '<section id="graph" hidden role="region" aria-label="Dependency graph"></section>'
    : "";
  const navGraph = opts.includeGraph && data.has_index
    ? '<a id="nav-graph" href="#graph" role="button">Dependency graph</a>'
    : "";

  const badges = `${data.totals.fresh} fresh · ${staleLabel(data)} · ${data.totals.missing} missing${data.totals.violations > 0 ? ` · ${data.totals.violations} violation${data.totals.violations === 1 ? "" : "s"}` : ""}`;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data:">
<title>autocontext — ${escapeHtml(data.project.name)}</title>
<style>${STYLES}</style>
</head>
<body>
<a class="skip-link" href="#detail">Skip to detail</a>
<header role="banner">
<h1>autocontext — ${escapeHtml(data.project.name)}</h1>
<nav role="navigation" aria-label="primary">
<a id="nav-overview" href="#" role="button" aria-current="page">Overview</a>
${navGraph}
</nav>
<div class="badges">${escapeHtml(badges)}</div>
</header>
<main>
<aside role="complementary" aria-label="Directory tree">
${tree}
</aside>
<section id="detail" role="region" aria-live="polite" aria-label="Scope detail" tabindex="-1"></section>
${graphSection}
</main>
<footer>Generated by autocontext ${escapeHtml(data.project.autocontext_version)} at ${escapeHtml(data.project.generated_at)}.</footer>
<script type="application/json" id="autocontext-data">${jsonBlob}</script>
<script type="module">${CLIENT_JS}</script>
</body>
</html>
`;
}

function prepareDataBlob(data: ViewData, opts: RenderOptions): ViewData {
  // Strip heavy fields when --no-source is set.
  const scopes: ViewScope[] = data.scopes.map((s) => ({
    ...s,
    raw_yaml: opts.includeSource ? s.raw_yaml : "",
    exports: opts.includeSource
      ? s.exports
      : s.exports.map((e) => ({ name: e.name, kind: e.kind })),
  }));
  return {
    ...data,
    scopes,
    dir_edges: opts.includeGraph ? data.dir_edges : [],
  };
}

function renderTree(scopes: ViewScope[]): string {
  if (scopes.length === 0) return "<p class=\"muted\">No tracked scopes.</p>";
  // Build a tree structure keyed by depth for nested <details>.
  const byPath = new Map<string, ViewScope>(scopes.map((s) => [s.scope, s]));
  const roots: string[] = [];
  const childrenByParent = new Map<string, string[]>();
  for (const s of scopes) {
    if (s.scope === ".") roots.push(s.scope);
    else {
      const parent = parentOf(s.scope);
      if (parent === "." || byPath.has(parent)) {
        const list = childrenByParent.get(parent) ?? [];
        list.push(s.scope);
        childrenByParent.set(parent, list);
      } else {
        roots.push(s.scope);
      }
    }
  }
  if (roots.length === 0 && byPath.has(".")) roots.push(".");
  if (!roots.includes(".") && byPath.has(".")) roots.unshift(".");
  roots.sort();

  const render = (scope: string, depth: number): string => {
    const s = byPath.get(scope);
    if (!s) return "";
    const label = scope === "." ? "(root)" : scope.split("/").pop() ?? scope;
    const icon = iconFor(s.freshness);
    const violationBadge = s.violations.length > 0
      ? `<span class="violations" aria-label="${s.violations.length} policy violation${s.violations.length === 1 ? "" : "s"}">${s.violations.length}</span>`
      : "";
    const children = childrenByParent.get(scope) ?? [];
    const openAttr = depth === 0 ? " open" : "";
    let html = `<details${openAttr}><summary>${icon} <a class="label" href="#scope=${encodeURIComponent(scope)}">${escapeHtml(label)}</a>${violationBadge}</summary>`;
    for (const child of children.sort()) html += render(child, depth + 1);
    html += "</details>";
    return html;
  };

  return roots.map((r) => render(r, 0)).join("\n");
}

function iconFor(freshness: ViewScope["freshness"]): string {
  switch (freshness) {
    case "fresh": return ICONS.fresh;
    case "cosmetic_stale": return ICONS.cosmetic_stale;
    case "semantic_stale": return ICONS.semantic_stale;
    case "missing": return ICONS.missing;
    case "stale":
    default:
      return ICONS.stale;
  }
}

function parentOf(scope: string): string {
  if (!scope.includes("/")) return ".";
  return scope.slice(0, scope.lastIndexOf("/"));
}

function staleLabel(data: ViewData): string {
  if (data.has_semantic_staleness) {
    return `${data.totals.cosmetic_stale} cosmetic · ${data.totals.semantic_stale} semantic`;
  }
  return `${data.totals.stale + data.totals.cosmetic_stale + data.totals.semantic_stale} stale`;
}

function escapeHtml(s: string): string {
  return String(s ?? "").replace(/[&<>"']/g, (c) => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#39;",
  }[c] as string));
}
